<?php
namespace Walleye;

/**
 * Test class for Email.
 * Generated by PHPUnit on 2011-01-18 at 21:06:47.
 */
class EmailTest extends \PHPUnit_Framework_TestCase
{

    protected $walleye;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->walleye = Walleye::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     *
     */
    public function testConstructTo()
    {
        $email = new Email('jon@walleye.com', 'subject', 'hello you');
        $this->assertEquals('jon@walleye.com', $email->getTo());
    }

    /**
     *
     */
    public function testConstructSubject()
    {
        $email = new Email('jon@walleye.com', 'subject', 'hello you');
        $this->assertEquals('subject', $email->getSubject());
    }

    /**
     *
     */
    public function testConstructMessage()
    {
        $email = new Email('jon@walleye.com', 'subject', 'hello you');
        $this->assertEquals('hello you', $email->getMessage());
    }

    /**
     *
     */
    public function testWithTemplateTo()
    {
        $email = Email::withTemplate('jon@walleye.com', 'subject', 'test.txt', array());
        $this->assertEquals('jon@walleye.com', $email->getTo());
    }

    /**
     *
     */
    public function testWithTemplateSubject()
    {
        $email = Email::withTemplate('jon@walleye.com', 'subject', 'test.txt', array('username' => 'jon'));
        $this->assertEquals('Hello jon', $email->getMessage());
    }

    /**
     *
     */
    public function testWithTemplateMessage()
    {
        $email = Email::withTemplate('jon@walleye.com', 'subject', 'test.txt', array('username' => 'jon'));
        $this->assertEquals('Hello jon', $email->getMessage());
    }

    /**
     * @todo Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
