<?php
namespace Walleye;


require_once '../includes/core/walleye.config.php';

/**
 * Test class for Config.
 * Generated by PHPUnit on 2011-01-18 at 21:07:46.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{

    protected $appOptions = array();

    protected $dbOptions = array();

    protected $routes = array();

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->appOptions = Config::getAppOptions();
        $this->dbOptions = Config::getDbOptions();
        $this->routes = Config::getRoutes();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Only test that the PRODUCTION option is set to false.
     */
    public function testGetAppOptionsProduction()
    {
        $this->assertFalse($this->appOptions['PRODUCTION']);
    }

    /**
     * Tests to make sure the database engine is set to mysql
     */
    public function testGetDbOptionsEngine()
    {
        $this->assertEquals('mysql', $this->dbOptions['ENGINE']);
    }

    /**
     * @todo Implement testGetRoutes().
     */
    public function testGetRoutesDefault()
    {
        $this->assertEquals('Site', $this->routes['default']);
    }

    /**
     * @todo Implement testGetRoutes().
     */
    public function testGetRoutesAllRegExp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetRoutes().
     */
    public function testGetRoutesControllersExist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
