<?php
namespace Walleye;

/**
 * Test class for Controller.
 * Generated by PHPUnit on 2011-01-18 at 21:07:12.
 */
class FunctionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testHash_Data()
    {
        $data = hash_data('1');
        $this->assertEquals('8513c69d070a008df008aef8624ed24afc81b170d242faf5fafe853d4fe9bf8aa7badfb0fd045d7b350b19fbf8ef6b2a51f17a07a1f6819abc9ba5ce43324244', $data);
    }

    public function testHash_DataWrongHash()
    {
        $data = hash_data('1');
        $this->assertFalse('8513c69d070a008df008aef8624ed24afc81b170d242faf5fafe853d4fe9bf8aa7badfb0fd045d7b350b19fbf8ef6b2a51f17a07a1f6819abc9ba5ce43324245' == $data);
    }

    public function testEncryptAndDecrypt()
    {
        $data = 'walleyewalleyewalleye';
        $key = 'key';

        $encrypted_data = encrypt('walleyewalleyewalleye', $key);
        $this->assertTrue($data != $encrypted_data);

        $decryped_data = decrypt($encrypted_data, $key);
        $this->assertEquals($data, $decryped_data);
    }

    public function testPrintArray()
    {

    }

    public function testDaysFromNow()
    {

    }

    public function testSlugify()
    {

    }

}

?>
