<?php
namespace Walleye;


require_once '../includes/core/walleye.model.php';

/**
 * Test class for Model.
 * Generated by PHPUnit on 2011-01-18 at 21:04:22.
 */
class ModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
